import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  pageContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    height: '100%',
    width: '100%',
    paddingTop: '5%',
    gap: 4,
    position: 'relative',
  },
  pageTitle: {
    flex: 1,
  },
  replayButton: {
    position: 'absolute',
    top: '5%',
    right: '5%',
    padding: '2%',
  },
  button: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0)',
  },
  cardsSet: {
    marginTop: '2%',
    height: '80%',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap',
    width: '70%',
  },
  invisible: {
    display: 'none',
  },
  faceB: {
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
  },
  faceA: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    position: 'relative',
  },
  backImage: {
    borderRadius: 10,
    height: '100%',
    width: '100%',
  },
  animalImage: {
    height: '100%',
    width: '100%',
    resizeMode: 'stretch',
    borderRadius: 10,
  },
  textCard: {
    color: 'white',
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    textTransform: 'uppercase',
    textAlign: 'center',
    paddingVertical: '2%',
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    height: 'auto',
    backgroundColor: 'rgba(0, 0, 0, 0.62)',
  },

  buttonClose: {
    backgroundColor: '#2196F3',
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalView: {
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    backgroundColor: '#FFF',
  },
  modalTitle: {
    textAlign: 'center',
    color: '#ff8a01',
    fontWeight: 'bold',
    marginBottom: '5%',
  },
  modalText: {
    marginBottom: 15,
    color: '#000',
    textAlign: 'center',
  },
  funfact: {
    backgroundColor: 'rgba(0, 0, 0, 0.62)',
    bottom: 0,
    left: 0,
    position: 'absolute',
    width: '100%',
    height: 'auto',
    padding: '2%',
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomRightRadius: 15,
    borderBottomLeftRadius: 15,
  },
  funfactText: {
    color: '#FFF',
    textAlign: 'center',
    fontStyle: 'italic',
  },
  modalCloseButton: {
    position: 'absolute',
    top: 0,
    right: 0,
    backgroundColor: '#ff8a01',
  },
});
