import { ImageMap, Animal } from '../models/Animal';

// Image mapping object
const imageMap: ImageMap = {
  redPanda: require('../../assets/images/memory/redPanda.jpg'),
  tiger: require('../../assets/images/memory/tiger.jpg'),
  whale: require('../../assets/images/memory/whale.jpg'),
  jellyfish: require('../../assets/images/memory/jellyfish.jpg'),
  gorilla: require('../../assets/images/memory/gorilla.jpg'),
  bear: require('../../assets/images/memory/bear.jpg'),
  cat: require('../../assets/images/memory/cat.jpg'),
  shark: require('../../assets/images/memory/shark.jpg'),
  lion: require('../../assets/images/memory/lion.jpg'),
  polarBear: require('../../assets/images/memory/polarBear.jpg'),
  peacock: require('../../assets/images/memory/peacock.jpg'),
  penguin: require('../../assets/images/memory/penguin.jpg'),
  squirrel: require('../../assets/images/memory/squirrel.jpg'),
  wolf: require('../../assets/images/memory/wolf.jpg'),
  koala: require('../../assets/images/memory/koala.jpg'),
  giraf: require('../../assets/images/memory/giraf.jpg'),
  spider: require('../../assets/images/memory/spider.jpg'),
};

const animals: Animal[] = [
  {
    id: 1,
    name: 'Panda roux',
    image: 'redPanda',
    funFact: 'En chinois, son nom peut être traduit par "petit ours-chat".',
    habitat: 'Forêts en montagne',
    region: 'Asie',
    size: '50-64 cm',
    weight: '3-6 kg',
    speed: '24 km/h',
    food: 'Bambou, fruits, œufs',
    endangered: true,
    icon: 'redPanda',
  },
  {
    id: 2,
    name: 'Tigre',
    image: 'tiger',
    funFact: 'Aucun tigre n’a les mêmes rayures—comme une empreinte digitale !',
    habitat: 'Forêts et prairies',
    region: 'Asie',
    size: '2,5-3,9 m',
    weight: '65-306 kg',
    speed: '65 km/h',
    food: 'Viande : cerfs, sangliers',
    endangered: true,
    icon: 'tiger',
  },
  {
    id: 3,
    name: 'Baleine bleue',
    image: 'whale',
    funFact: 'Son cœur est aussi gros qu’une voiture !',
    habitat: 'Océans',
    region: 'Tous les grands océans sauf l’Arctique',
    size: '24-30 m',
    weight: '100-150 tonnes',
    speed: '50 km/h',
    food: 'Krill microscopique',
    endangered: true,
    icon: 'whale',
  },
  {
    id: 4,
    name: 'Méduse',
    image: 'jellyfish',
    funFact: 'Certaines méduses sont biologiquement immortelles !',
    habitat: 'Océans',
    region: 'Monde entier',
    size: '1 cm - 2 m',
    weight: 'Très léger !',
    speed: '8 km/h',
    food: 'Petits poissons et plancton',
    endangered: false,
    icon: 'jellyfish',
  },
  {
    id: 5,
    name: 'Gorille',
    image: 'gorilla',
    funFact: 'Les gorilles partagent environ 98 % de leur ADN avec les humains.',
    habitat: 'Forêts tropicales et régions montagneuses',
    region: 'Afrique',
    size: '1,4-1,8 m',
    weight: '70-220 kg',
    speed: '40 km/h',
    food: 'Plantes, fruits et quelques insectes',
    endangered: true,
    icon: 'gorilla',
  },
  {
    id: 6,
    name: 'Grizzli',
    image: 'bear',
    funFact: 'Il peut sentir un poisson à plus de 30 km !',
    habitat: 'Forêts et montagnes',
    region: 'Amérique du Nord',
    size: '1,5-2,5 m',
    weight: '80-360 kg',
    speed: '56 km/h',
    food: 'Baies et poissons',
    endangered: false,
    icon: 'bear',
  },
  {
    id: 7,
    name: 'Chat',
    image: 'cat',
    funFact: 'Les chats dorment presque toute la journée… de vrais paresseux !',
    habitat: 'Maisons et rues',
    region: 'Monde entier',
    size: '23-25 cm',
    weight: '3-6 kg',
    speed: '48 km/h',
    food: 'Poisson, viande, croquettes',
    endangered: false,
    icon: 'cat',
  },
  {
    id: 8,
    name: 'Requin',
    image: 'shark',
    funFact: 'Les requins existaient avant les dinosaures !',
    habitat: 'Océans',
    region: 'Monde entier',
    size: '4-6 m',
    weight: '700-2200 kg',
    speed: '56 km/h',
    food: 'Phoques et poissons',
    endangered: true,
    icon: 'shark',
  },
  {
    id: 9,
    name: 'Araignée Jorō',
    image: 'spider',
    funFact: 'Ses toiles brillent comme de l’or au soleil !',
    habitat: 'Arbres, coins tranquilles',
    region: 'Asie (introduite aux USA)',
    size: 'jusqu’à 10 cm pattes déployées',
    weight: 'léger',
    speed: '',
    food: 'Insectes',
    endangered: false,
    icon: 'spider',
  },
  {
    id: 10,
    name: 'Koala',
    image: 'koala',
    funFact: 'Il a 4 pouces à l’avant pour grimper comme un pro !',
    habitat: 'Forêts d’eucalyptus',
    region: 'Australie',
    size: '60–85 cm',
    weight: '≈ 14 kg',
    speed: '',
    food: 'Feuilles d’eucalyptus',
    endangered: false,
    icon: 'koala',
  },
  {
    id: 11,
    name: 'Lion',
    image: 'lion',
    funFact: 'Son rugissement porte jusqu’à 8 km !',
    habitat: 'Savane',
    region: 'Afrique',
    size: '2,7–3 m',
    weight: 'femelles ≈ 180 kg, mâles jusqu’à 250 kg',
    speed: '',
    food: 'Grand herbivores',
    endangered: true,
    icon: 'lion',
  },
  {
    id: 12,
    name: 'Paon',
    image: 'peacock',
    funFact: 'Il peut avoir 150 belles plumes de 1,5 m !',
    habitat: 'Parcs, forêts',
    region: 'Asie, Afrique',
    size: '',
    weight: '',
    speed: '',
    food: 'Graines, insectes, petits reptiles',
    endangered: false,
    icon: 'peacock',
  },
  {
    id: 13,
    name: 'Pingouin (empereur)',
    image: 'penguin',
    funFact: 'Il incube l’œuf… sur ses pieds, au pôle Sud !',
    habitat: 'Antarctique',
    region: 'pôle Sud',
    size: '≈ 1,15 m',
    weight: '≲ 40 kg',
    speed: '',
    food: 'Poissons, calmars',
    endangered: false,
    icon: 'penguin',
  },
  {
    id: 15,
    name: 'Ours polaire',
    image: 'polarBear',
    funFact: 'Sous sa fourrure blanche, sa peau est noire !',
    habitat: 'Glaces de l’Arctique',
    region: 'Canada, Russie, Groenland, Norvège, Alaska',
    size: 'jusqu’à 2,5 m + pattes',
    weight: 'mâles jusqu’à 720 kg',
    speed: '',
    food: 'Phoques',
    endangered: true,
    icon: 'bear',
  },
  {
    id: 16,
    name: 'Écureuil',
    image: 'squirrel',
    funFact: 'Il peut tourner ses pattes arrière de 180°, pour descendre tête la première !',
    habitat: 'Forêts, parcs',
    region: 'Monde entier sauf Australie/Antarctique',
    size: '',
    weight: '',
    speed: '',
    food: 'Noix, graines, fruits',
    endangered: false,
    icon: 'squirrel',
  },
  {
    id: 17,
    name: 'Loup',
    image: 'wolf',
    funFact: 'Son odorat est 100× plus puissant que le nôtre !',
    habitat: 'Forêts, toundra, montagnes',
    region: 'Europe, Asie, Amérique du Nord',
    size: '',
    weight: '≈ 30–50 kg',
    speed: '',
    food: 'Mammifères, ongulés',
    endangered: false,
    icon: 'wolf',
  },
];

export { animals, imageMap };
