import { ImageMap, Animal } from '../models/Animal';

const iconMap: ImageMap = {
  redPanda: require('../../assets/icons/memory/redPanda.png'),
  tiger: require('../../assets/icons/memory/tiger.png'),
  whale: require('../../assets/icons/memory/whale.png'),
  jellyfish: require('../../assets/icons/memory/jellyfish.png'),
  gorilla: require('../../assets/icons/memory/gorilla.png'),
  bear: require('../../assets/icons/memory/bear.png'),
  cat: require('../../assets/icons/memory/cat.png'),
  shark: require('../../assets/icons/memory/shark.png'),
};

// Image mapping object
const imageMap: ImageMap = {
  redPanda: require('../../assets/images/memory/redPanda.jpg'),
  tiger: require('../../assets/images/memory/tiger.jpg'),
  whale: require('../../assets/images/memory/whale.jpg'),
  jellyfish: require('../../assets/images/memory/jellyfish.jpg'),
  gorilla: require('../../assets/images/memory/gorilla.jpg'),
  bear: require('../../assets/images/memory/bear.jpg'),
  cat: require('../../assets/images/memory/cat.jpg'),
  shark: require('../../assets/images/memory/shark.jpg'),
};

const animals: Animal[] = [
  {
    id: 1,
    name: 'Panda roux',
    image: 'redPanda',
    funFact: 'En chinois, son nom peut être traduit par "petit ours-chat".',
    habitat: 'Forêts en montagne',
    region: 'Asie',
    size: '50-64 cm',
    weight: '3-6 kg',
    speed: '24 km/h',
    food: 'Bambou, fruits, œufs',
    endangered: true,
    icon: 'redPanda',
  },
  {
    id: 2,
    name: 'Tigre',
    image: 'tiger',
    funFact: 'Aucun tigre n’a les mêmes rayures—comme une empreinte digitale !',
    habitat: 'Forêts et prairies',
    region: 'Asie',
    size: '2,5-3,9 m',
    weight: '65-306 kg',
    speed: '65 km/h',
    food: 'Viande : cerfs, sangliers',
    endangered: true,
    icon: 'tiger',
  },
  {
    id: 3,
    name: 'Baleine bleue',
    image: 'whale',
    funFact: 'Son cœur est aussi gros qu’une voiture !',
    habitat: 'Océans',
    region: 'Tous les grands océans sauf l’Arctique',
    size: '24-30 m',
    weight: '100-150 tonnes',
    speed: '50 km/h',
    food: 'Krill microscopique',
    endangered: true,
    icon: 'whale',
  },
  {
    id: 4,
    name: 'Méduse',
    image: 'jellyfish',
    funFact: 'Certaines méduses sont biologiquement immortelles !',
    habitat: 'Océans',
    region: 'Monde entier',
    size: '1 cm - 2 m',
    weight: 'Très léger !',
    speed: '8 km/h',
    food: 'Petits poissons et plancton',
    endangered: false,
    icon: 'jellyfish',
  },
  {
    id: 5,
    name: 'Gorille',
    image: 'gorilla',
    funFact: 'Les gorilles partagent environ 98 % de leur ADN avec les humains.',
    habitat: 'Forêts tropicales et régions montagneuses',
    region: 'Afrique',
    size: '1,4-1,8 m',
    weight: '70-220 kg',
    speed: '40 km/h',
    food: 'Plantes, fruits et quelques insectes',
    endangered: true,
    icon: 'gorilla',
  },
  {
    id: 6,
    name: 'Ours grizzli',
    image: 'bear',
    funFact: 'Les ours peuvent courir plus vite que les humains !',
    habitat: 'Forêts et montagnes',
    region: 'Amérique du Nord',
    size: '1,5-2,5 m',
    weight: '80-360 kg',
    speed: '56 km/h',
    food: 'Baies et poissons',
    endangered: false,
    icon: 'bear',
  },
  {
    id: 7,
    name: 'Chat',
    image: 'cat',
    funFact: 'Les chats dorment presque toute la journée… de vrais paresseux !',
    habitat: 'Maisons et rues',
    region: 'Monde entier',
    size: '23-25 cm',
    weight: '3-6 kg',
    speed: '48 km/h',
    food: 'Poisson, viande, croquettes',
    endangered: false,
    icon: 'cat',
  },
  {
    id: 8,
    name: 'Requin',
    image: 'shark',
    funFact: 'Les requins existaient avant les dinosaures !',
    habitat: 'Océans',
    region: 'Monde entier',
    size: '4-6 m',
    weight: '700-2200 kg',
    speed: '56 km/h',
    food: 'Phoques et poissons',
    endangered: true,
    icon: 'shark',
  },
];

export { animals, imageMap, iconMap };
